#!/usr/bin/env python3
"""Regenerate scripts/arabicize_demo.sql from seed_catalog_ar.go.

The Go maps and the SQL backfill must stay in lock-step: any demo product
barcode or category slug edited in seed_catalog_ar.go must be re-published by
running this script. It parses the two map declarations (category slug -> Arabic
name and product barcode -> [Arabic name, Arabic description]) and emits a
DO-block that backfills name_ar / description_ar for every tenant whose rows
still have NULL (idempotent). RLS FORCE means the loop must set
app.current_tenant per tenant before each UPDATE.
"""

import re
import sys
from pathlib import Path

GO = Path(__file__).resolve().parents[1] / "internal/transport/auth/seed_catalog_ar.go"
OUT = Path(__file__).resolve().parents[1] / "scripts/arabicize_demo.sql"


def parse_source() -> tuple[dict[str, str], dict[str, tuple[str, str]]]:
    cats: dict[str, str] = {}
    prods: dict[str, tuple[str, str]] = {}
    section = None
    for raw in GO.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("var arabicCategoryNames"):
            section = "cats"
            continue
        if line.startswith("var arabicProducts"):
            section = "prods"
            continue
        if section is None or not line or line.startswith("//"):
            continue
        if line.startswith("}"):
            section = None
            continue
        m = re.match(r'^"([^"]+)"\s*:\s*(.+),\s*$', line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        if section == "cats":
            cats[key] = val.strip('"')
        else:
            mm = re.match(r"^\{\s*\"([^\"]*)\"\s*,\s*\"([^\"]*)\"\s*\}$", val)
            if not mm:
                raise SystemExit(f"unparseable product entry: {line}")
            prods[key] = (mm.group(1), mm.group(2))
    return cats, prods


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build(cats: dict[str, str], prods: dict[str, tuple[str, str]]) -> str:
    lines: list[str] = [
        "-- Auto-generated by scripts/gen_arabicize_sql.py from",
        "-- internal/transport/auth/seed_catalog_ar.go. Do not edit by hand.",
        "-- Idempotent: fills name_ar / description_ar for categories and products",
        "-- that still have NULL. RLS FORCE means each UPDATE needs app.current_tenant,",
        "-- so it loops all tenants in one transaction.",
        "",
        "DO $$",
        "DECLARE",
        "    t uuid;",
        "BEGIN",
        "    FOR t IN SELECT id FROM tenants LOOP",
        "        PERFORM set_config('app.current_tenant', t::text, true);",
        "",
        f"        UPDATE categories",
        f"        SET name_ar = CASE slug",
        *[f"            WHEN {sql_quote(slug)} THEN {sql_quote(name)}" for slug, name in cats.items()],
        "            ELSE name_ar",
        "        END",
        f"        WHERE slug IN ({', '.join(sql_quote(s) for s in cats)});",
        "",
        "        UPDATE products",
        "        SET name_ar = CASE barcode",
        *[f"            WHEN {sql_quote(barcode)} THEN {sql_quote(n)}" for barcode, (n, _) in prods.items()],
        "            ELSE name_ar",
        "        END,",
        "        description_ar = CASE barcode",
        *[f"            WHEN {sql_quote(barcode)} THEN {sql_quote(d)}" for barcode, (_, d) in prods.items()],
        "            ELSE description_ar",
        "        END",
        f"        WHERE barcode IS NOT NULL AND barcode IN ({', '.join(sql_quote(b) for b in prods)});",
        "    END LOOP;",
        "END $$;",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    cats, prods = parse_source()
    OUT.write_text(build(cats, prods), encoding="utf-8")
    print(f"wrote {OUT} ({len(cats)} categories, {len(prods)} products)")
    return 0


if __name__ == "__main__":
    sys.exit(main())