import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pos_go_app/l10n/strings.dart';

void main() {
  test('default locale is Arabic', () {
    const all = AppStrings.supportedLocales;
    expect(all.first, const Locale('ar'));
    expect(all, contains(const Locale('en')));
  });

  test('Arabic strings are provided for core labels', () {
    final ar = AppStrings(const Locale('ar'));
    expect(ar.isArabic, isTrue);
    expect(ar.signIn, 'تسجيل الدخول');
    expect(ar.checkout, 'إتمام الدفع');
    expect(ar.total, 'الإجمالي');
    expect(ar.rememberLogins, 'تذكر بيانات تسجيل الدخول');
    expect(ar.outOfStock, 'نفد المخزون');
    expect(ar.offlineSaved, isNotEmpty);
    expect(ar.payment, 'طريقة الدفع');
    expect(ar.cash, 'نقدًا');
    expect(ar.card, 'بطاقة');
    expect(ar.mobilePayment, 'محفظة');
    expect(ar.remainingLabel, isNotEmpty);
    expect(ar.posSettings, 'إعدادات نقطة البيع');
    expect(ar.defaultPaymentMethod, 'طريقة الدفع الافتراضية');
    expect(ar.stockBadges, 'شارات المخزون');
    expect(ar.receiptFooter, 'تذييل الإيصال');
    expect(ar.save, 'حفظ');
    expect(ar.roleOwner, 'مالك');
    expect(ar.roleManager, 'مدير');
    expect(ar.roleCashier, 'أمين صندوق');
    expect(ar.splashTitle, 'نظام نقطة البيع');
    expect(ar.splashTagline, isNotEmpty);
    expect(ar.poweredByXamltech, contains('XAMLtech'));
    expect(ar.posSession, isNotEmpty);
    expect(ar.openSession, 'فتح جلسة');
    expect(ar.startingCash, 'رصيد البدء النقدي');
    expect(ar.finishSession, 'إنهاء الجلسة');
    expect(ar.countedCash, isNotEmpty);
    expect(ar.zReport, 'تقرير الجلسة');
    expect(ar.expectedCash, 'النقد المتوقع');
    expect(ar.cashOver, 'زيادة');
    expect(ar.cashShort, 'عجز');
    expect(ar.statusOpen, 'مفتوحة');
    expect(ar.statusClosed, 'مغلقة');
    expect(ar.dashboard, 'لوحة التحكم');
    expect(ar.revenueToday, 'إيرادات اليوم');
    expect(ar.topProducts, 'الأكثر مبيعًا');
    expect(ar.perCashier, 'حسب أمين الصندوق');
    expect(ar.paymentMix, 'مزيج الدفع');
    expect(ar.methodLabel('card'), 'بطاقة');
    expect(ar.methodLabel('mobile'), 'محفظة');
    expect(ar.methodLabel('cash'), 'نقدًا');
    expect(ar.methodLabel('unknown'), 'نقدًا');
    expect(ar.customers, 'العملاء');
    expect(ar.addCustomer, 'إضافة عميل');
    expect(ar.loyaltyPoints, 'نقاط الولاء');
    expect(ar.refund, 'استرداد');
    expect(ar.refundSale, 'استرداد البيع');
    expect(ar.refundReason, isNotEmpty);
    expect(ar.refundPin, isNotEmpty);
    expect(ar.refundProcessing, isNotEmpty);
    expect(ar.refundSuccess, isNotEmpty);
    expect(ar.refundedStatus, 'مُسترجع');
    expect(ar.newOrder, 'طلب جديد');
    expect(ar.openOrders, 'الطلبات المفتوحة');
    expect(ar.orderLabel(1), 'طلب 1');
    expect(ar.orderLabel(5), 'طلب 5');
    expect(ar.focusMode, 'وضع التركيز');
    expect(ar.focusModeOn, isNotEmpty);
    expect(ar.focusModeOff, isNotEmpty);
    expect(ar.focusModeDndHint, isNotEmpty);
    expect(ar.focusModeGrant, 'منح الإذن');
    expect(ar.inventory, 'المخزون');
    expect(ar.onHand, 'المتوفر');
    expect(ar.adjustStock, 'تعديل المخزون');
    expect(ar.refillPurchase, 'توريد / شراء');
    expect(ar.removeStock, isNotEmpty);
    expect(ar.setOnHandNow, 'الرصيد الفعلي الآن');
    expect(ar.stockUpdated, 'تم تحديث المخزون');
    expect(ar.adjustmentsHistory, 'سجل التعديلات');
    expect(ar.reasonRestock, 'توريد');
    expect(ar.reasonDamaged, 'تالف');
    expect(ar.reasonCount, 'جرد');
    expect(ar.cannotGoNegative, isNotEmpty);
    expect(ar.advancedInventory, 'خيارات المخزون المتقدمة');
    expect(ar.allowNegativeStock, 'البيع بالمخزون السالب');
    expect(ar.backorder, 'طلبية مُعلّقة');
    expect(ar.invalidQuantity, isNotEmpty);
    expect(ar.saving, 'جارٍ الحفظ...');
    expect(ar.onboardingWelcomeTitle, contains('مرحبًا'));
    expect(ar.onboardingFreeTrial, contains('15 يومًا'));
    expect(ar.coffeeShop, 'مقهى');
    expect(ar.restaurant, 'مطعم');
    expect(ar.retail, 'متجر تجزئة');
    expect(ar.bookStore, 'مكتبة');
    expect(ar.mobileShop, 'محل موبايل');
    expect(ar.computerShop, 'محل كمبيوتر');
    expect(ar.grocery, 'بقالة وسوبر ماركت');
    expect(ar.bakery, 'مخبز');
    expect(ar.shawerma, 'شاورما');
    expect(ar.falafel, 'فول وفلافل');
    expect(ar.pharmacy, 'صيدلية');
    expect(ar.butcher, 'جزارة');
    expect(ar.fruitsVeg, 'خضار وفاكهة');
    expect(ar.clothing, 'ملابس');
    expect(ar.sweets, 'حلويات');
    expect(ar.jewelry, 'ذهب ومجوهرات');
    expect(ar.hardware, 'عدد ومعدات');
    expect(ar.unitLabel('kg'), 'كجم');
    expect(ar.createStore, 'إنشاء المتجر');
    expect(ar.storeName, 'اسم المتجر');
    expect(ar.ownerName, 'اسم المالك');
    expect(ar.signUp, contains('بدء البيع'));
    expect(ar.signingUp, isNotEmpty);
    expect(ar.alreadyHaveStore, contains('سجّل الدخول'));
    expect(ar.passwordMin, isNotEmpty);
    expect(ar.storeCreated, isNotEmpty);
    expect(ar.trialExpired, contains('الفترة التجريبية'));
  });

  test('English strings are provided for core labels', () {
    final en = AppStrings(const Locale('en'));
    expect(en.isArabic, isFalse);
    expect(en.signIn, 'Sign in');
    expect(en.checkout, 'Checkout');
    expect(en.total, 'Total');
    expect(en.rememberLogins, 'Remember logins');
    expect(en.outOfStock, 'Out of stock');
    expect(en.offlineSynced, 'Offline sales synced');
    expect(en.payment, 'Payment method');
    expect(en.cash, 'Cash');
    expect(en.card, 'Card');
    expect(en.mobilePayment, 'Mobile wallet');
    expect(en.posSettings, 'POS settings');
    expect(en.defaultPaymentMethod, 'Default payment method');
    expect(en.stockBadges, 'Stock badges');
    expect(en.receiptFooter, 'Receipt footer');
    expect(en.save, 'Save');
    expect(en.roleOwner, 'Owner');
    expect(en.roleManager, 'Manager');
    expect(en.roleCashier, 'Cashier');
    expect(en.splashTitle, 'Point of Sale');
    expect(en.splashTagline, isNotEmpty);
    expect(en.poweredByXamltech, contains('XAMLtech'));
    expect(en.posSession, 'POS session');
    expect(en.openSession, 'Open session');
    expect(en.startingCash, 'Starting cash');
    expect(en.finishSession, 'Finish session');
    expect(en.countedCash, isNotEmpty);
    expect(en.zReport, 'Session report');
    expect(en.expectedCash, 'Expected cash');
    expect(en.cashOver, 'Over');
    expect(en.cashShort, 'Short');
    expect(en.statusOpen, 'Open');
    expect(en.statusClosed, 'Closed');
    expect(en.dashboard, 'Dashboard');
    expect(en.revenueToday, "Today's revenue");
    expect(en.topProducts, 'Top products');
    expect(en.perCashier, 'Per cashier');
    expect(en.paymentMix, 'Payment mix');
    expect(en.methodLabel('card'), 'Card');
    expect(en.methodLabel('mobile'), 'Mobile wallet');
    expect(en.methodLabel('cash'), 'Cash');
    expect(en.methodLabel('unknown'), 'Cash');
    expect(en.customers, 'Customers');
    expect(en.addCustomer, 'Add customer');
    expect(en.loyaltyPoints, 'Loyalty points');
    expect(en.refund, 'Refund');
    expect(en.refundSale, 'Refund sale');
    expect(en.refundReason, isNotEmpty);
    expect(en.refundPin, isNotEmpty);
    expect(en.offlineNeedsAttention, isNotEmpty);
    expect(en.refundedStatus, 'Refunded');
    expect(en.newOrder, 'New order');
    expect(en.openOrders, 'Open orders');
    expect(en.orderLabel(1), 'Order 1');
    expect(en.orderLabel(5), 'Order 5');
    expect(en.focusMode, 'Focus mode');
    expect(en.focusModeOn, isNotEmpty);
    expect(en.focusModeOff, isNotEmpty);
    expect(en.focusModeDndHint, isNotEmpty);
    expect(en.focusModeGrant, 'Grant access');
    expect(en.inventory, 'Inventory');
    expect(en.onHand, 'On hand');
    expect(en.adjustStock, 'Adjust stock');
    expect(en.refillPurchase, 'Refill (purchase)');
    expect(en.removeStock, isNotEmpty);
    expect(en.setOnHandNow, 'Set on-hand now');
    expect(en.stockUpdated, 'Stock updated');
    expect(en.adjustmentsHistory, 'Adjustment log');
    expect(en.reasonRestock, 'Restock');
    expect(en.reasonDamaged, 'Damaged');
    expect(en.reasonCount, 'Count');
    expect(en.cannotGoNegative, isNotEmpty);
    expect(en.advancedInventory, 'Advanced inventory');
    expect(en.allowNegativeStock, 'Allow negative stock');
    expect(en.backorder, 'Backorder');
    expect(en.invalidQuantity, isNotEmpty);
    expect(en.saving, 'Saving...');
    expect(en.onboardingWelcomeTitle, contains('Welcome'));
    expect(en.onboardingFreeTrial, contains('15 days'));
    expect(en.coffeeShop, 'Coffee shop');
    expect(en.restaurant, 'Restaurant');
    expect(en.retail, 'Retail store');
    expect(en.bookStore, 'Bookstore');
    expect(en.mobileShop, 'Mobile shop');
    expect(en.computerShop, 'Computer shop');
    expect(en.grocery, 'Grocery');
    expect(en.bakery, 'Bakery');
    expect(en.shawerma, 'Shawerma');
    expect(en.falafel, 'Falafel');
    expect(en.pharmacy, 'Pharmacy');
    expect(en.butcher, 'Butcher');
    expect(en.fruitsVeg, 'Fruits & vegetables');
    expect(en.clothing, 'Clothing');
    expect(en.sweets, 'Sweets');
    expect(en.jewelry, 'Jewelry');
    expect(en.hardware, 'Hardware');
    expect(en.unitLabel('liter'), 'liter');
    expect(en.createStore, 'Create store');
    expect(en.storeName, 'Store name');
    expect(en.ownerName, 'Owner name');
    expect(en.signUp, contains('start selling'));
    expect(en.signingUp, isNotEmpty);
    expect(en.alreadyHaveStore, contains('Sign in'));
    expect(en.passwordMin, isNotEmpty);
    expect(en.storeCreated, isNotEmpty);
    expect(en.trialExpired, contains('trial'));
  });

  test('onboarding interests and price-plan strings are provided', () {
    final en = AppStrings(const Locale('en'));
    expect(en.continueLabel, 'Continue');
    expect(en.interestTitle, contains('store'));
    expect(en.featureInventory, 'Inventory control');
    expect(en.featureLoyalty, 'Customers & loyalty points');
    expect(en.featureTables, 'Tables & split bills');
    expect(en.featureDiscounts, 'Discounts & manager PIN');
    expect(en.plansTitle, 'Choose your plan');
    expect(en.planTrial, 'Free trial');
    expect(en.planStandard, 'Standard');
    expect(en.planPremium, 'Premium');
    expect(en.planEnterprise, 'Enterprise');
    expect(en.planPerMonth, '/month');
    expect(en.trialBadge, contains('15 days'));
    expect(en.trialLimitUsers, 'Up to 2 users');
    expect(en.trialLimitProducts, 'Up to 150 products');
    expect(en.startTrial, contains('15-day trial'));
    expect(en.planAfterTrialLabel('Premium'), contains('Premium'));
    expect(en.planLimitsLabel(5, 500), contains('5'));
    expect(en.trialPlanNotice, contains('trial'));

    final ar = AppStrings(const Locale('ar'));
    expect(ar.continueLabel, 'متابعة');
    expect(ar.interestsHint, isNotEmpty);
    expect(ar.interestTitle, contains('يهمك'));
    expect(ar.featureInventory, contains('المخزون'));
    expect(ar.featureRefunds, contains('استرداد'));
    expect(ar.plansTitle, contains('باقتك'));
    expect(ar.planTrial, contains('تجربة'));
    expect(ar.planPremium, contains('بريميوم'));
    expect(ar.trialBadge, contains('15 يومًا'));
    expect(ar.trialLimitNoCard, contains('بطاقة'));
    expect(ar.startTrial, contains('15 يومًا'));
    expect(ar.planAfterTrialLabel('بريميوم'), contains('بريميوم'));
    expect(ar.trialLimitsTitle, contains('التجربة'));
    expect(ar.trialPlanNotice, contains('تجربة'));
  });

  test('money formatted with EGP symbol', () {
    expect(AppStrings(const Locale('en')).formatMoney(1250, 'EGP'), 'E£12.50');
    expect(AppStrings(const Locale('ar')).formatMoney(1250, 'EGP'), '12.50 E£');
  });

  test('unsupported locales fall back to English', () {
    final fr = AppStrings(const Locale('fr'));
    expect(fr.isArabic, isFalse);
    expect(fr.signIn, 'Sign in');
  });
}