package server

// English copy for the public brand, pricing and privacy pages. Keys are
// referenced by the templates in site_templates.go — keep every key present
// in both languages (see site_strings_ar.go).

var siteStrings = map[string]map[string]string{
	"en": {
		"brand":        "POS.Go",
		"brandSub":     "by XAMLtech",
		"navLabel":     "Main navigation",
		"navFeatures":  "Features",
		"navGallery":   "Gallery",
		"navAll":       "Everything",
		"navVerticals": "Verticals",
		"navPricing":   "Pricing",
		"navPrivacy":   "Privacy",
		"navAdmin":     "Sign in",
		"navLang":      "العربية",

		"heroPill":     "Offline-first · Egypt · EGP",
		"heroTitle":    "Point of sale that keeps selling when the network drops.",
		"heroLead":     "POS.Go runs your counter, kitchen and shelf — registers, cash sessions, receipts, sync, loyalty and inventory in one app. Built for Egyptian businesses by XAMLtech.",
		"tagline":      "Point of sale for Egypt.",
		"ctaPrimary":   "Sign in",
		"ctaSecondary": "See pricing",
		"storePlay":    "Get it on Google Play",
		"storePlaySub": "Android · free trial",
		"downloadApk":  "Download APK",
		"apkHint":      "Direct install · com.xamltech.pos_go",
		"stat1":        "17",
		"stat1L":       "business verticals",
		"stat2":        "15",
		"stat2L":       "day free trial",
		"stat3":        "5",
		"stat3L":       "staff access levels",
		"stat4":        "E£",
		"stat4L":       "always Egyptian pounds",

		"secGallery":   "Screenshots",
		"galTitle":     "A look inside POS.Go",
		"galLead":      "Real screens from the Android app — checkout, cart, analytics, sales, customers, cash sessions and the community.",
		"galCheckout":  "Checkout",
		"galCart":      "Cart & payment",
		"galDash":      "Today's dashboard",
		"galSales":     "Sales history",
		"galCustomers": "Customers & loyalty",
		"galSessions":  "Cash sessions",
		"galCommunity": "Community hub",
		"galNational":  "Egypt community",
		"galPrev":      "Previous screenshot",
		"galNext":      "Next screenshot",
		"currency":     "E£",

		"secFeatures":     "Features",
		"featTitle":       "Everything a busy counter needs.",
		"featLead":        "Registers, inventory, payments, loyalty and approvals — designed for a real Egyptian shop day, not a demo.",
		"f1t":             "Offline-first POS",
		"f1d":             "Keep selling through outages. Every sale is queued on the device and replays idempotently the moment you are back online.",
		"f2t":             "Registers & cash sessions",
		"f2d":             "Open a register per terminal, track opening, expected and closing cash, and close the day with a Z-report.",
		"f3t":             "Inventory that thinks",
		"f3d":             "On-hand stock per product, expiring lots served FEFO, size and colour variants, and negative-stock rules you control.",
		"f4t":             "Payments, tips & split bills",
		"f4d":             "Cash, card and mobile-wallet split tender; restaurant tips and per-cover split bills right from the counter.",
		"f5t":             "Loyalty customers",
		"f5d":             "Every sale earns points with a full ledger — see balances and activity from inside the app.",
		"f6t":             "Discounts you control",
		"f6d":             "Server-enforced caps, manager-PIN approvals and five staff access levels. The client never sets its own rules.",
		"f7t":             "POS.Go Copilot",
		"f7d":             "AI-assisted support built in. Ask how to run a report, settle the drawer or set up a vertical, and get step-by-step answers in Arabic or English.",
		"secAll":          "Everything included",
		"allTitle":        "Every module, in one app.",
		"allLead":         "Every plan runs the full POS.Go engine — you pick limits, never features. Here is what ships out of the box.",
		"all1t":           "Sell fast",
		"all1d":           "A counter built for the busiest hour — even when the network is not.",
		"all1a":           "Sales keep flowing through outages, queued on the device",
		"all1b":           "Replays exactly once the moment you are back online",
		"all1c":           "Barcode scan, category filters and instant search",
		"all2t":           "Payments & splitting",
		"all2d":           "Accept every way Egypt pays, right from one screen.",
		"all2a":           "Cash, card and mobile-wallet split tender in EGP",
		"all2b":           "Tips on the tender and per-cover split bills",
		"all2c":           "Floors and tables with occupancy you can assign and release",
		"all3t":           "Registers & cash",
		"all3d":           "Opening, selling and closing cash, reconciled at the end of the day.",
		"all3a":           "One open session per terminal, opening cash set once",
		"all3b":           "Expected vs counted cash at close",
		"all3c":           "Z-report and full session history from the app",
		"all4t":           "Inventory & stock",
		"all4d":           "What is on the shelf, what is running low and what you control — in one grid.",
		"all4a":           "On-hand stock on every product card",
		"all4b":           "Adjustments for damaged, restock and count",
		"all4c":           "Negative-stock rules, low-stock alerts and block-out-of-stock",
		"all5t":           "Lots & variants",
		"all5d":           "Expiry-aware stock for pharmacies and variants for fashion — no extra apps.",
		"all5a":           "Expiry lots served FEFO for pharmacy",
		"all5b":           "Size, colour and SKU variants with their own barcodes",
		"all5c":           "Each variant priced and tracked like its own product",
		"all6t":           "Discounts & approvals",
		"all6d":           "Give your team room to discount without giving away the store.",
		"all6a":           "Server-enforced caps — the client never sets rules",
		"all6b":           "Cap, warn, block and PIN-approval modes",
		"all6c":           "Manager PIN for refunds, discounts and register close",
		"all7t":           "Reports & analytics",
		"all7d":           "Know what sold, who sold it and how it was paid — while it is still today.",
		"all7a":           "Live dashboard: today's revenue, average and item count",
		"all7b":           "Top products, per-cashier breakdown and payment mix",
		"all7c":           "Sales history and seven-day trends",
		"all8t":           "Customers & loyalty",
		"all8d":           "Reward regulars at the counter and keep the ledger in sight.",
		"all8a":           "Every sale accrues points at your rate",
		"all8b":           "Full points ledger per customer",
		"all8c":           "Searchable customer directory in the app",
		"all9t":           "Receipts & refunds",
		"all9d":           "Professional receipts your customers recognise, printed in a tap.",
		"all9a":           "Printer-style receipts on screen and in JSON",
		"all9b":           "Thermal ESC/POS print with QR code",
		"all9c":           "Idempotent refunds that restock and claw back points",
		"all10t":          "Multi-device sync",
		"all10d":          "All your terminals agree on the same data — even mid-outage.",
		"all10a":          "Change feed keeps every register in step",
		"all10b":          "Push commands are replay-safe and exactly-once",
		"all10c":          "One-click tenant backup and export",
		"all11t":          "Team & community",
		"all11d":          "Grow with the Egyptian market: hire, connect and moderate as a community.",
		"all11a":          "Five staff access levels plus granular permissions",
		"all11b":          "Staff profiles, companies and a jobs board",
		"all11c":          "Egypt national community: expert levels and invite codes",
		"all12t":          "Owner's control plane",
		"all12d":          "The subscription and tenant console for owners and partners.",
		"all12a":          "Web console for tenants, plans and subscriptions",
		"all12b":          "Billing in Egyptian pounds with invoices",
		"all12c":          "Suspend, activate, stop and back up from the console",
		"navCopilot":      "Copilot",
		"coptPill":        "AI support · always on",
		"coptTitleLead":   "Meet",
		"coptTitleAccent": "POS.Go Copilot.",
		"coptLead":        "AI assistance built into every counter — ask in Arabic or English how to close the register, read a Z-report, cap discounts or fix stock rules, and get step-by-step answers grounded in your store's real data.",
		"coptS1L":         "Setup", "coptS1V": "5 min", "coptS1S": "to start asking",
		"coptS2L": "Languages", "coptS2V": "2", "coptS2S": "Arabic & English",
		"coptS3L": "Help", "coptS3V": "24/7", "coptS3S": "no queues",
		"coptC1t": "Answers grounded in your data",
		"coptC1d": "Copilot sees your register, sales, stock and settings, so help is specific to your store — never generic.",
		"coptC2t": "Arabic & English",
		"coptC2d": "Ask in the language your team speaks at the counter and get the same clear steps back.",
		"coptC3t": "Always-on support",
		"coptC3d": "No phone queues or office hours — instant help for the whole register day.",
		"coptCta": "Start your free trial",

		"secVerticals": "Verticals",
		"vitTitle":     "Tailored to how Egypt sells.",
		"vitLead":      "Onboarding, product templates and stock logic for the verticals that run the market.",
		"vit1":         "Restaurants", "vit2": "Cafés", "vit3": "Pharmacies", "vit4": "Bookstores",
		"vit5": "Mobile shops", "vit6": "Computer shops", "vit7": "Grocery", "vit8": "Sweets",
		"vit9": "Butchery", "vit10": "Fruits & vegetables", "vit11": "Textile & fashion", "vit12": "Jewellery",
		"vit13": "Hardware", "vit14": "Beauty", "vit15": "Bakeries", "vit16": "Shawerma & falafel", "vit17": "Supermarkets",

		"secHow":   "How it works",
		"howTitle": "One register-day, end to end.",
		"howLead":  "A POS that follows how a busy counter actually runs.",
		"how1t":    "Open the register",
		"how1d":    "Set opening cash once per terminal, name the device, and start selling in a tap.",
		"how2t":    "Sell, split, serve",
		"how2d":    "Scan barcodes, take cash, card or mobile wallet, split a table across covers and add a tip.",
		"how3t":    "Close with a Z-report",
		"how3d":    "Count the drawer, compare expected vs counted cash and finalise the day with one screen.",

		"secFAQ":   "FAQ",
		"faqTitle": "Asked by real counters.",
		"q1":       "What happens if the network drops mid-sale?",
		"a1":       "Sales keep flowing. Every sale is written to the device and queued; the moment you are back online it syncs exactly once, so nothing is double-charged or lost.",
		"q2":       "What hardware do I need?",
		"a2":       "Any current Android phone or tablet. Receipts print over the network to standard thermal receipt printers against each terminal.",
		"q3":       "How is my data protected between devices and staff?",
		"a3":       "Business data is row-level isolated per tenant on the server, passwords and PINs are stored hashed, and staff see only what their access level allows.",
		"q4":       "Can I change plans later?",
		"a4":       "Yes. Plans are monthly in EGP, and you can change or cancel any time from the admin console — every plan starts with a 15-day free trial.",
		"q5":       "Are receipts e-invoice ready?",
		"a5":       "Receipts show EGP amounts in Arabic and English and follow a VAT-friendly layout. Direct ETA e-invoicing is on the roadmap.",

		"secPlans":   "Pricing",
		"plansTitle": "Plans that start free.",
		"plansLead":  "Start a 15-day trial, pay in Egyptian pounds, and scale as you grow.",
		"plansCTA":   "Compare all plans →",
		"ctaPlan":    "Start trial",
		"planMost":   "Most popular",

		"pricingTitle":   "Simple pricing in Egyptian pounds.",
		"pricingLead":    "Every plan starts with a 15-day free trial — no card required. Sign in to the console to activate.",
		"priceNote":      "Need custom limits or a vertical not listed? Contact support@xamltech.com.",
		"backHome":       "← Back to POS.Go",
		"pricingMeta":    "POS.Go pricing — clear monthly plans for restaurants, retail, pharmacy and every business. Free trial, pay in EGP.",
		"secCompare":     "Compare",
		"compareTitle":   "Every plan, side by side.",
		"compareLead":    "The same engine on every plan — you pick limits, not features.",
		"compareFeature": "Feature",

		"privacyTitle":   "Privacy Policy",
		"privacyMeta":    "Privacy policy for POS.Go by XAMLtech — what data we process, why, and your rights.",
		"privacyUpdated": "Last updated January 1, 2026.",
		"privacyIntro":   "POS.Go is a point-of-sale service operated by XAMLtech. This policy explains what personal data we process, why, and the choices you have. By using POS.Go you agree to the practices described here.",
		"s1t":            "1. Who we are",
		"s1b":            "POS.Go is a point-of-sale service operated by XAMLtech. This policy explains the personal data we process, the reasons for it, and the choices you have.",
		"s2t":            "2. Data we collect",
		"s2a":            "Account data: name, email, password (stored hashed), tenant and role, access level and permission settings.",
		"s2b":            "Terminal & device data: a generated device identifier and the device name you choose for each register.",
		"s2c":            "Business data: products, categories, customers, sales, payments, invoices, inventory and receipts you enter in POS.Go.",
		"s2d":            "Usage & technical data: crash reports, screen names, app version, and basic request logs (IP address) for security.",
		"s3t":            "3. How we use data",
		"s3b":            "We use your data only to run the service: authenticate users, sync data across your devices, produce receipts and reports, apply your discount and access rules, prevent fraud and abuse, and provide support. We never sell your data.",
		"s4t":            "4. Sharing",
		"s4b":            "We share data only with sub-processors needed to host and operate the service (for example the cloud provider hosting our servers). Those parties are bound by appropriate confidentiality and security commitments. Business data stays isolated per tenant and is never shared between tenants.",
		"s5t":            "5. Retention",
		"s5b":            "We keep your account and transaction data for as long as your tenant is active, and for the periods required by tax law for receipt and invoice records. Telemetry and crash data are retained for shorter operational periods.",
		"s6t":            "6. Security",
		"s6b":            "Traffic is encrypted in transit (TLS), passwords and PINs are stored hashed, access to tenant data is enforced by row-level security, and credentials are kept in secure storage. You can remove users, close registers and export your data from the app at any time.",
		"s7t":            "7. Your rights",
		"s7b":            "You may access, correct, export or delete your personal data, and object to processing, by contacting us. Account deletion removes your personal data subject to legal retention periods.",
		"s8t":            "8. Contact",
		"s8b":            "Questions about this policy or your data: support@xamltech.com.",
		"privacyBack":    "← Back to POS.Go",

		"footerTag":    "Offline-first point of sale for Egypt.",
		"footerRights": "All rights reserved.",
		"footerSaas":   "SaaS admin",
		"contact":      "support@xamltech.com",

		// Company home (xamltech.com). Kept at the end of the map because it is
		// a separate surface from the POS.Go product site.
		"companyName":       "XAMLtech",
		"companyBrandSub":   "Software studio",
		"companyTagline":    "Software for Egyptian business.",
		"companyMeta":       "XAMLtech is an Egyptian software studio building offline-first point of sale, the operating platform behind it, and the community around it.",
		"companyTitle":      "Software that keeps Egyptian businesses moving.",
		"companyPill":       "Cairo · Egypt · since 2024",
		"companyHeroTitle":  "Software that keeps Egyptian businesses moving.",
		"companyHeroLead":   "We build the tools a real shop actually runs on — a point of sale that keeps selling through an outage, the platform that operates it, and the support that stays reachable. Built here, in Arabic and English, priced in pounds.",
		"companyCtaProduct": "Explore POS.Go",
		"companyCtaContact": "Talk to us",
		"companyStat1":      "AR / EN",
		"companyStat1L":     "every screen, both directions",
		"companyStat2":      "EGP",
		"companyStat2L":     "priced and taxed for Egypt",
		"companyStat3":      "Offline",
		"companyStat3L":     "the network is optional",

		"companyNavWork":     "What we build",
		"companyNavApproach": "How we work",
		"companyNavContact":  "Contact",
		"companyNavConsole":  "Console",
		"companyNavProduct":  "POS.Go",

		"companySecWork":   "What we build",
		"companyWorkTitle": "Three things, built to fit together.",
		"companyWorkLead":  "A product, the platform behind it, and the people who use it — designed as one system instead of three vendors.",
		"companyWork1t":    "POS.Go",
		"companyWork1d":    "The point-of-sale app: registers, split payments, stock, lots and variants, loyalty, receipts and refunds — on any Android terminal, online or not.",
		"companyWork2t":    "The operating platform",
		"companyWork2d":    "Multi-tenant billing, plans and trial lifecycle, backups and per-tenant analytics — the control plane our customers' own admins run on.",
		"companyWork3t":    "Community & support",
		"companyWork3d":    "A national directory for Egyptian retail staff, a jobs board, and built-in AI assistance in Arabic or English — no queues, no office hours.",
		"companyWorkLink":  "See what POS.Go does →",

		"companySecApproach":   "How we work",
		"companyApproachTitle": "Built for the shop day, not the demo.",
		"companyApproachLead":  "Three rules we do not bend, because they are the ones a counter feels.",
		"companyApp1t":         "The counter comes first",
		"companyApp1d":         "Every feature starts as a question about a real register day — the busiest hour, a dropped network, a drawer that does not add up.",
		"companyApp2t":         "Local by default",
		"companyApp2d":         "Arabic first, Egyptian pounds, local payment methods and taxes. If it does not work in Cairo it does not ship.",
		"companyApp3t":         "Own your data",
		"companyApp3d":         "Row-level isolation per tenant, hashed credentials, encrypted transport, and a backup you can actually restore.",

		"companySecStart":   "Start here",
		"companyStartTitle": "Two doors, one studio.",
		"companyStartLead":  "Open the app for your store, or sign in to the platform console to run tenants and plans.",
		"companyStartTag":   "For shops",
		"companyStart1t":    "POS.Go",
		"companyStart1d":    "The point-of-sale app for your counter, kitchen and shelf.",
		"companyStart1a":    "Free trial, no card required",
		"companyStart1b":    "Offline-first, Arabic and English",
		"companyStart1cta":  "Open POS.Go",
		"companyStart2t":    "Platform console",
		"companyStart2d":    "For platform operators and partners running stores on POS.Go.",
		"companyStart2a":    "Tenants, plans and subscriptions",
		"companyStart2b":    "Backups and per-tenant analytics",
		"companyStart2cta":  "Contact support",

		"companyFooterTag": "An Egyptian software studio.",

		"planUsers": "Users", "planProducts": "Products", "planUnlimited": "Unlimited",
	},
	"ar": siteStringsAR,
}
