package server

// English copy for the public brand, pricing and privacy pages. Keys are
// referenced by the templates in site_templates.go — keep every key present
// in both languages (see site_strings_ar.go).

var siteStrings = map[string]map[string]string{
	"en": {
		"brand":        "POS.Go",
		"brandSub":     "by XAMLtech",
		"navLabel":     "Main navigation",
		"navFeatures":  "Features",
		"navVerticals": "Verticals",
		"navPricing":   "Pricing",
		"navPrivacy":   "Privacy",
		"navAdmin":     "Admin sign in",
		"navLang":      "العربية",

		"heroPill":     "Offline-first · Egypt · EGP",
		"heroTitle":    "Point of sale that keeps selling when the network drops.",
		"heroLead":     "POS.Go runs your counter, kitchen and shelf — registers, cash sessions, receipts, sync, loyalty and inventory in one app. Built for Egyptian businesses by XAMLtech.",
		"tagline":      "Point of sale for Egypt.",
		"ctaPrimary":   "Admin sign in",
		"ctaSecondary": "See pricing",
		"trust1":       "17 business verticals",
		"trust2":       "Multi-device sync",
		"trust3":       "Row-level data security",

		"recOrder":  "ORDER #2841",
		"recDate":   "18 Sep 2026 · 14:32",
		"recItem1":  "2× Café Latte",
		"recVal1":   "120.00",
		"recItem2":  "1× Tahini Wrap",
		"recVal2":   "95.00",
		"recItem3":  "4× Baklava",
		"recVal3":   "60.00",
		"recSub":    "Subtotal",
		"recTip":    "Tip",
		"recTotal":  "TOTAL",
		"recPaid":   "Cash",
		"recPoints": "+2 loyalty points",
		"recThanks": "Thank you — come again!",
		"recStamp":  "PAID",
		"currency":  "E£",

		"secFeatures": "Features",
		"featTitle":   "Everything a busy counter needs.",
		"featLead":    "Registers, inventory, payments, loyalty and approvals — designed for a real Egyptian shop day, not a demo.",
		"f1t":         "Offline-first POS",
		"f1d":         "Keep selling through outages. Every sale is queued on the device and replays idempotently the moment you are back online.",
		"f2t":         "Registers & cash sessions",
		"f2d":         "Open a register per terminal, track opening, expected and closing cash, and close the day with a Z-report.",
		"f3t":         "Inventory that thinks",
		"f3d":         "On-hand stock per product, expiring lots served FEFO, size and colour variants, and negative-stock rules you control.",
		"f4t":         "Payments, tips & split bills",
		"f4d":         "Cash, card and mobile-wallet split tender; restaurant tips and per-cover split bills right from the counter.",
		"f5t":         "Loyalty customers",
		"f5d":         "Every sale earns points with a full ledger — see balances and activity from inside the app.",
		"f6t":         "Discounts you control",
		"f6d":         "Server-enforced caps, manager-PIN approvals and five staff access levels. The client never sets its own rules.",

		"secVerticals": "Verticals",
		"vitTitle":     "Tailored to how Egypt sells.",
		"vitLead":      "Onboarding, product templates and stock logic for the verticals that run the market.",
		"vit1":         "Restaurants", "vit2": "Cafés", "vit3": "Pharmacies", "vit4": "Bookstores",
		"vit5": "Mobile shops", "vit6": "Computer shops", "vit7": "Grocery", "vit8": "Sweets",
		"vit9": "Butchery", "vit10": "Fruits & vegetables", "vit11": "Textile & fashion", "vit12": "Jewellery",
		"vit13": "Hardware", "vit14": "Beauty", "vit15": "Bakeries", "vit16": "Shawerma & falafel", "vit17": "Supermarkets",

		"secPlans":   "Pricing",
		"plansTitle": "Plans that start free.",
		"plansLead":  "Start a 15-day trial, pay in Egyptian pounds, and scale as you grow.",
		"plansCTA":   "Compare all plans →",
		"ctaPlan":    "Start trial",
		"planMost":   "Most popular",

		"pricingTitle": "Simple pricing in Egyptian pounds.",
		"pricingLead":  "Every plan starts with a 15-day free trial — no card required. Sign in to the console to activate.",
		"priceNote":    "Need custom limits or a vertical not listed? Contact support@xamltech.com.",
		"backHome":     "← Back to POS.Go",
		"pricingMeta":  "POS.Go pricing — clear monthly plans for restaurants, retail, pharmacy and every business. Free trial, pay in EGP.",

		"privacyTitle":   "Privacy Policy",
		"privacyMeta":    "Privacy policy for POS.Go by XAMLtech — what data we process, why, and your rights.",
		"privacyUpdated": "Last updated January 1, 2026.",
		"privacyIntro":   "POS.Go is a point-of-sale service operated by XAMLtech. This policy explains what personal data we process, why, and the choices you have. By using POS.Go you agree to the practices described here.",
		"s1t":            "1. Who we are",
		"s1b":            "POS.Go is a point-of-sale service operated by XAMLtech. This policy explains the personal data we process, the reasons for it, and the choices you have.",
		"s2t":            "2. Data we collect",
		"s2a":            "Account data: name, email, password (stored hashed), tenant and role, access level and permission settings.",
		"s2b":            "Terminal & device data: a generated device identifier and the device name you choose for each register.",
		"s2c":            "Business data: products, categories, customers, sales, payments, invoices, inventory and receipts you enter in POS.Go.",
		"s2d":            "Usage & technical data: crash reports, screen names, app version, and basic request logs (IP address) for security.",
		"s3t":            "3. How we use data",
		"s3b":            "We use your data only to run the service: authenticate users, sync data across your devices, produce receipts and reports, apply your discount and access rules, prevent fraud and abuse, and provide support. We never sell your data.",
		"s4t":            "4. Sharing",
		"s4b":            "We share data only with sub-processors needed to host and operate the service (for example the cloud provider hosting our servers). Those parties are bound by appropriate confidentiality and security commitments. Business data stays isolated per tenant and is never shared between tenants.",
		"s5t":            "5. Retention",
		"s5b":            "We keep your account and transaction data for as long as your tenant is active, and for the periods required by tax law for receipt and invoice records. Telemetry and crash data are retained for shorter operational periods.",
		"s6t":            "6. Security",
		"s6b":            "Traffic is encrypted in transit (TLS), passwords and PINs are stored hashed, access to tenant data is enforced by row-level security, and credentials are kept in secure storage. You can remove users, close registers and export your data from the app at any time.",
		"s7t":            "7. Your rights",
		"s7b":            "You may access, correct, export or delete your personal data, and object to processing, by contacting us. Account deletion removes your personal data subject to legal retention periods.",
		"s8t":            "8. Contact",
		"s8b":            "Questions about this policy or your data: support@xamltech.com.",
		"privacyBack":    "← Back to POS.Go",

		"footerTag":    "Offline-first point of sale for Egypt.",
		"footerRights": "All rights reserved.",
		"contact":      "support@xamltech.com",

		"planUsers": "Users", "planProducts": "Products", "planUnlimited": "Unlimited",
	},
	"ar": siteStringsAR,
}
